### PR TITLE
Issue #2933086 by truls1502, chr.fritsch: Update fb_instant_articles from 8.x-1.x to 8.x-2.x

### PR DESCRIPTION
**Pull request by ol0lll**
Make sure these boxes are checked before submitting your pull request - thank you!

- [ ] All coding styles are fulfilled. ([How to check for cs issues?](https://github.com/BurdaMagazinOrg/thunder-dev-tools/blob/master/README.md#code-style-guidelines))
- [ ] All tests are running locally. ([How to run the test?](https://github.com/thunder/thunder-distribution/blob/8.x-3.x/docs/development.md#how-to-run-the-tests))
- [ ] Necessary update hooks are provided.
- [ ] User roles have correct access for new introduced permission.
- [ ] Every thunder module has a README.md in its root. Follow [this guidelines](https://www.drupal.org/node/2181737), but we don't need every topic.
- [ ] Code is covered with well-balanced amount of inline comments.

If you are really awesome, then your feature is covered by additional tests. Well done!

### CODE REVIEW

**Comment by ol0lll** [comment]
https://github.com/BurdaMagazinOrg/thunder-distribution/pull/680

**Comment by ol0lll** [comment]
- Facebook Instant Article drupal module was updated. 
- Facebook Instant Articles will not work anymore for pages having "minimal readership", see Instant Article Policies (https://developers.facebook.com/docs/instant-articles/policy/). Please provide a different URL."

It is now possible to integrate with facebook instant articles using the REST API or a RSS feed.
We had some integration (thunder_fia module) for the RSS feed, where we render paragraphs with correct facebook IA markup, this approach would still be applicable. The new module heavily facilitates the https://github.com/facebook/facebook-instant-articles-sdk-php, so we can probably remove lots of code.

Unfortunately we are not able to test these implementations since we do not have access to a webpage with sufficient readership. I openend a support request at facebook about providing a test setup for instant articles, but to no avail.

Imho there are three possible ways to go forward:

- Remove the current integration since we are not able to test. just ship the module uninstalled.
- Move integration to contrib.
- Align configuration for RSS feed to new implementation.

**Comment by ol0lll** [comment]
We went with 

> * Align configuration for RSS feed to new implementation.

**Comment by ol0lll** [comment]
Instagram, pinterest and twitter embeds currently do not render anything, since we did not use them before I will remove configuration.

**Comment by ol0lll** [comment]
Needed to move thunder_fia module to a [separate module](https://drupal.org/project/thunder_fia), otherwise it would not be possible for projects to stay on 1.x version of fb_instant_articles, since import of optional config for fb_instant_articles 2.x breaks. 

Thunder 2 PR is here: https://github.com/BurdaMagazinOrg/thunder-distribution/pull/705

**Review by dbosen — CHANGES_REQUESTED** [review]
When updating to fb_instant_articles 2 the rss feed gets a new URL. We should add that information in the update document, and explain, that the feed URL has to be updated in the facebook account.

**Review by dbosen — CHANGES_REQUESTED** [review]
Another thing we should add to the update document is, that after updating with fia enabled, you will get an error message like `The "fiafields" plugin does not exist. Valid plugin IDs for Drupal\views\Plugin\ViewsPluginManager are: ...`
I think we cannot do much against this, but we should inform people, that it is no problem.

**Comment by ol0lll** [comment]
Added info to https://github.com/thunder/thunder-distribution/pull/24

**Comment by ol0lll** [comment]
Two fixes are needed in fb_instant_articles:

https://github.com/BurdaMagazinOrg/module-fb_instant_articles/pull/140
https://github.com/BurdaMagazinOrg/module-fb_instant_articles/pull/141

**Comment by ol0lll** [comment]
Let's do https://github.com/BurdaMagazinOrg/thunder-distribution/pull/705 first

**Comment by ol0lll** [comment]
Moved BurdaMagazinOrg/thunder-distribution#705, which was against thunder 2.x branch to new pr targetting 4.x at thunder/thunder-distribution/#151

**Pull request closed without merging**
