### PR TITLE
Prepare nightwatch commands for new version of Nightwatch JS

### PR DESCRIPTION
**Pull request by mtodor**
Add support for Nightwatch JS 1.x

- [x] All coding styles are fulfilled. ([How to check for cs issues?](https://github.com/BurdaMagazinOrg/thunder-dev-tools/blob/master/README.md#code-style-guidelines))
- [x] All tests are running locally. ([How to run the test?](https://github.com/thunder/thunder-distribution/blob/8.x-3.x/docs/development.md#how-to-run-the-tests))

### CODE REVIEW

**Comment by chrfritsch** [comment]
Steps I am going to test:
 - Install Thunder current with D8.7.x -> should fail
 - Checkout this branch -> should work
 - Use 8.7.7 -> should also work

**Comment by chrfritsch** [comment]
Followed the steps of my previous comment and got what I expected. So, fine.

But with 8.7.x and the PR branch I also saw one error: 
```
Tests/ Create Most Used Content] Test Suite
============================================
Starting ChromeDriver 75.0.3770.90 (a6dcaf7e3ec6f70a194cc25e8149475c6590e025-refs/branch-heads/3770@{#1003}) on port 9515
Only local connections are allowed.
Please protect ports used by ChromeDriver and related test frameworks to prevent access by malicious code.
[1568646855.069][WARNING]: This version of ChromeDriver has not been tested with Chrome version 76.
Running:  createMostUsedContent

APM Server transport error (ECONNREFUSED): connect ECONNREFUSED 127.0.0.1:8200
APM Server transport error (ECONNREFUSED): connect ECONNREFUSED 127.0.0.1:8200
 Error while running .setCookieString() protocol action: invalid argument: missing 'value'

   Error: invalid argument: missing 'value'
       at processTicksAndRejections (internal/process/task_queues.js:85:5)
 Error while running .setCookieString() protocol action: invalid argument: missing 'value'

   Error: invalid argument: missing 'value'
       at processTicksAndRejections (internal/process/task_queues.js:85:5)
✔ Passed [equal]: The user "test-admin" was logged in.
APM Server transport error (ECONNREFUSED): connect ECONNREFUSED 127.0.0.1:8200
✔ Element <//*[@id="edit-submit"]> was visible after 26 milliseconds.
Auto fill field:  title
APM Server transport error (ECONNREFUSED): connect ECONNREFUSED 127.0.0.1:8200
APM Server transport error (ECONNREFUSED): connect ECONNREFUSED 127.0.0.1:8200
✔ Element <//*[@id="block-thunder-base-page-title"]/div[2]/h1/span> was visible after 36 milliseconds.
APM Server transport error (ECONNREFUSED): connect ECONNREFUSED 127.0.0.1:8200

OK. 3 assertions passed. (8.186s)
✨  Done in 18.40s.
```

**Comment by mtodor** [comment]
@chrfritsch The error was caused by missing environment variables. I have adjusted the documentation and listed them.

**Review by chrfritsch — APPROVED** [review]
The warnings are gone after adding the env vars. 👍

**Pull request merged**
